name: tiki_money
description: Money sdk for Tiki app.
version: 0.0.9
homepage: https://mytiki.com
repository: https://github.com/tiki/money
issue_tracker: https://github.com/tiki/money/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  httpp: ^0.0.4
  logging: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  tiki_style: ^0.0.18
  tiki_localgraph: ^0.0.7
  tiki_wallet: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
