name: money
description: Money sdk for Tiki app.
version: 0.0.6
repository: https://github.com/tiki/money
publish_to: none # package in active development

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  httpp:
    git:
      url: https://github.com/tiki/httpp
  logging: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  tiki_style:
    git:
      url: https://github.com/tiki/style
      ref: 0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
