name: money
description: Money sdk for Tiki app.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^2.4.0
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3
  logging: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.mytiki.money
        pluginClass: MoneyPlugin
      ios:
        pluginClass: MoneyPlugin
  assets:
    - res/images/
